### ISSUE TITLE
It makes new folders

### ISSUE THREAD

**Issue by CasanovaSan** [Iyashinouta/sd-model-downloader#16]
can there be a option where it installs only the preview file and safetensor directly inside the main lora folder?
it continues to make new folders for each lora i install and it's quite annoying because it will make stuff like this:
![image](https://github.com/Iyashinouta/sd-model-downloader/assets/138389174/7810606f-1cc1-41a7-82a2-17557affc02c)

**Comment by Iyashinouta** [comment]
I put todolist
