### ISSUE TITLE
submit your extension to index via PR

### ISSUE THREAD

**Issue by w-e-w** [Iyashinouta/sd-model-downloader#3]
[stable-diffusion-webui-extensions](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
and fix the path issues, such as paths
respect Flags such as `--data-dir` `--data-dir`
you shouldn't be using `os.getcwd()` and and assuming people just use the base directories
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/paths_internal.py
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/paths.py
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings

reference other model downloader type extensions

**Comment by Iyashinouta** [comment]
okay, I put it to todolist

**Comment by Iyashinouta** [comment]
finished updating
if you get a new bug, please open a new issue
