### ISSUE TITLE
stable-diffusion-webui-extensions

### ISSUE THREAD

**Issue by w-e-w** [Iyashinouta/sd-model-downloader#5]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions

**Comment by Iyashinouta** [comment]
did u mean submit to index.json?

**Comment by w-e-w** [comment]
yes since
you just randomly post to Wiki I consider that to be "improper"

**Comment by Iyashinouta** [comment]
haha, sorry about that
