### ISSUE TITLE
aria2c error

### ISSUE THREAD

**Issue by jojo935** [Iyashinouta/sd-model-downloader#7]
So, I'm seemingly unable to download any model via the extension, even when installing from the extension manager in the webui... I just get the following errors:

NameError: name 'downloadpath' is not defined
'aria2c' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Iyashinouta** [comment]
install aria2 first via pip/apt get
then restart webui

**Comment by Iyashinouta** [comment]
elif still have bug (downloadpath) is not defined
i will fix it as soon as possible (put it to todolist)

**Comment by Iyashinouta** [comment]
elif still have bug (downloadpath) is not defined
i will fix it as soon as possible (put it to todolist)

**Comment by Iyashinouta** [comment]
update fix, added `install.py` for aria2c
