### ISSUE TITLE
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by YKefasu** [Iyashinouta/sd-model-downloader#8]
![Screenshot_2023-06-11_215609](https://github.com/Iyashinouta/sd-model-downloader/assets/129555908/0a1083b0-1f26-40cc-ba42-583151257592)

**Comment by Iyashinouta** [comment]
noted, I'll fix it later

- [todolist] : fix variable Nonetype

**Comment by Iyashinouta** [comment]
update fix, see Releases
open the discussion until the problem is solved
